name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
            - uses: pnpm/action-setup@v3.0.0
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 10
            - name: Install Dependencies
              run: pnpm install
            - name: test
              run: pnpm run test
